FROM golang:1.23.4-alpine

RUN go version

WORKDIR /app

COPY go.* ./
RUN go mod download

RUN go install github.com/air-verse/air@latest

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main ./cmd/main.go


EXPOSE 8000

CMD ["main"]
